import {
  Gender,
  MarriageStatus,
  MemberEventType,
  UserRole,
  UserStatus,
} from '@prisma/client';
import type { DemoResetTemplate } from './index';

export const defaultDemoTemplate: DemoResetTemplate = {
  key: 'default-demo',
  familyName: '默认演示家族',
  settings: {
    kinshipAliases: [
      { relationCode: 'F', standardTerm: '父亲', familyAlias: '阿爸', enabled: true },
      { relationCode: 'M', standardTerm: '母亲', familyAlias: '阿妈', enabled: true },
      { relationCode: 'F>F', standardTerm: '祖父', familyAlias: '阿公', enabled: true },
      { relationCode: 'F>M', standardTerm: '祖母', familyAlias: '阿婆', enabled: true },
      { relationCode: 'M>OB', standardTerm: '舅舅', familyAlias: '大舅', enabled: true },
    ],
    assetTags: [
      { name: '合影', enabled: true, sortOrder: 10 },
      { name: '证书', enabled: true, sortOrder: 20 },
      { name: '毕业', enabled: true, sortOrder: 30 },
      { name: '婚礼', enabled: true, sortOrder: 40 },
      { name: '祖宅', enabled: true, sortOrder: 50 },
      { name: '墓碑', enabled: true, sortOrder: 60 },
      { name: '族谱', enabled: true, sortOrder: 70 },
      { name: '口述资料', enabled: true, sortOrder: 80 },
    ],
    assetSources: [
      { name: '族人提供', enabled: true, sortOrder: 10 },
      { name: '老相册翻拍', enabled: true, sortOrder: 20 },
      { name: '证件扫描', enabled: true, sortOrder: 30 },
      { name: '地方志摘录', enabled: true, sortOrder: 40 },
      { name: '墓碑抄录', enabled: true, sortOrder: 50 },
      { name: '口述整理', enabled: true, sortOrder: 60 },
    ],
  },
  users: [
    {
      username: 'admin',
      phone: '18800000001',
      displayName: '默认家族管理员',
      password: 'admin123456',
      role: UserRole.ADMIN,
      status: UserStatus.ACTIVE,
    },
    {
      username: 'viewer',
      phone: '18800000002',
      displayName: '默认家族普通用户',
      password: 'viewer123456',
      role: UserRole.VIEWER,
      status: UserStatus.ACTIVE,
    },
  ],
  data: {
    members: [
      {
        code: 'zhenshan',
        name: '王振山',
        gender: Gender.MALE,
        birthDate: '1938-05-03',
        generationName: '振',
        birthOrder: 1,
        nativePlace: '江苏徐州',
        notes: '家族长辈示例数据',
      },
      {
        code: 'xiulan',
        name: '李秀兰',
        gender: Gender.FEMALE,
        birthDate: '1940-10-12',
        nativePlace: '江苏徐州',
      },
      {
        code: 'guohua',
        name: '王国华',
        gender: Gender.MALE,
        birthDate: '1965-03-15',
        generationName: '国',
        birthOrder: 1,
        nativePlace: '江苏徐州',
        fatherCode: 'zhenshan',
        motherCode: 'xiulan',
      },
      {
        code: 'guoqiang',
        name: '王国强',
        gender: Gender.MALE,
        birthDate: '1968-08-09',
        generationName: '国',
        birthOrder: 2,
        nativePlace: '江苏徐州',
        fatherCode: 'zhenshan',
        motherCode: 'xiulan',
      },
      {
        code: 'guifang',
        name: '王桂芳',
        gender: Gender.FEMALE,
        birthDate: '1970-04-20',
        generationName: '桂',
        birthOrder: 3,
        nativePlace: '江苏徐州',
        fatherCode: 'zhenshan',
        motherCode: 'xiulan',
      },
      {
        code: 'meilan',
        name: '张美兰',
        gender: Gender.FEMALE,
        birthDate: '1967-01-23',
        nativePlace: '安徽宿州',
      },
      {
        code: 'chenfang',
        name: '陈芳',
        gender: Gender.FEMALE,
        birthDate: '1972-07-30',
        nativePlace: '山东枣庄',
      },
      {
        code: 'leiming',
        name: '王磊',
        gender: Gender.MALE,
        birthDate: '1990-11-05',
        generationName: '磊',
        birthOrder: 1,
        nativePlace: '江苏徐州',
        fatherCode: 'guohua',
        motherCode: 'meilan',
      },
      {
        code: 'wangmin',
        name: '王敏',
        gender: Gender.FEMALE,
        birthDate: '1994-02-17',
        generationName: '敏',
        birthOrder: 2,
        nativePlace: '江苏徐州',
        fatherCode: 'guohua',
        motherCode: 'meilan',
      },
      {
        code: 'wanghao',
        name: '王浩',
        gender: Gender.MALE,
        birthDate: '1998-06-01',
        generationName: '浩',
        birthOrder: 1,
        nativePlace: '江苏徐州',
        fatherCode: 'guoqiang',
        motherCode: 'chenfang',
      },
      {
        code: 'liuyan',
        name: '刘妍',
        gender: Gender.FEMALE,
        birthDate: '1992-09-13',
        nativePlace: '江苏徐州',
      },
      {
        code: 'chenxi',
        name: '王晨曦',
        gender: Gender.MALE,
        birthDate: '2020-01-19',
        generationName: '晨',
        birthOrder: 1,
        nativePlace: '江苏徐州',
        fatherCode: 'leiming',
        motherCode: 'liuyan',
      },
    ],
    marriages: [
      {
        memberCode: 'zhenshan',
        spouseCode: 'xiulan',
        status: MarriageStatus.ACTIVE,
        startDate: '1962-01-01',
      },
      {
        memberCode: 'guohua',
        spouseCode: 'meilan',
        status: MarriageStatus.ACTIVE,
        startDate: '1988-01-01',
      },
      {
        memberCode: 'guoqiang',
        spouseCode: 'chenfang',
        status: MarriageStatus.ACTIVE,
        startDate: '1996-01-01',
      },
      {
        memberCode: 'leiming',
        spouseCode: 'liuyan',
        status: MarriageStatus.ACTIVE,
        startDate: '2018-01-01',
      },
    ],
    events: [
      {
        memberCode: 'guohua',
        eventType: MemberEventType.MOVE,
        title: '从老宅搬至市区',
        description: '示例事件，用于展示成员时间线的自定义条目。',
        eventDate: '1998-09-01',
        createdByUsername: 'admin',
      },
      {
        memberCode: 'leiming',
        eventType: MemberEventType.CAREER,
        title: '外出工作',
        description: '毕业后前往苏州工作，后续回到徐州定居。',
        eventDate: '2014-07-01',
        createdByUsername: 'admin',
      },
    ],
    assets: [],
  },
};
